---
sudo: false

# Set the JDK version
jdk:
 - oraclejdk8

# Compile everything to pull in dependencies for caching
install:
 - "./pants bootstrap"

cache:
 directories:
  - '~/.cache/'
  - '~/.m2/'

# Find changed targets, run all directly & transitively impacted tests
script:
 # Make sure we have the origin/develop ref
 - "git fetch origin develop:refs/remotes/origin/develop"

 # Get the set of pants targets which have changed with respect to origin/develop (local changes)
 - "TARGETS=$(./pants changed --changed-parent=origin/develop --changed-include-dependees=transitive)"
 
 # Run all those tests, or :: if there weren't changed targets
 - "./pants test ${TARGETS:-::}"
