---
sudo: false

# Set the JDK version
jdk:
 - oraclejdk8

# Compile everything to pull in dependencies for caching
install:
 - "./pants bootstrap"

cache:
 directories:
  - '~/.cache/'
  - '~/.m2/'

# Find changed targets, run all directly & transitively impacted tests
script:
 - "git fetch origin develop:refs/remotes/origin/develop" # Make sure we have the origin/develop ref
 - "./pants changed --changed-parent=origin/develop --changed-include-dependees=transitive | xargs ./pants test"
