---
sudo: false

# Set the JDK version
jdk:
 - oraclejdk8

# Compile everything to pull in dependencies for caching
install:
 - "./pants bootstrap"

cache:
 directories:
  - '~/.cache/'
  - '~/.m2/'

# Selectively run the changed tests
script:
 - "./pants test ::"

